version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    networks:
      - innercloud
  memcached:
    image: memcached:1
    networks:
      - innercloud
  redis:
    image: redis:2.6
    networks:
      - innercloud
networks:
  innercloud:
    external:
      name: cloudbuild
