apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcr-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcr-proxy
    spec:
      containers:
        - name: gcr-proxy
          image: gcr.io/pipeline-test-198007/gcrproxy:latest
          ports:
            - containerPort: 8000
            - containerPort: 8443
          env:
            - name: SERVICE_ACCOUNT_PATH
              value: "/secrets/account"
          envFrom:
            - configMapRef:
                name: gcr-proxy-configmap
            - secretRef:
                name: gcr-proxy-secrets
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /secrets
              name: secrets-file
              readOnly: true
      volumes:
        - name: secrets-file
          secret:
            secretName: gcr-proxy-secrets-file
