apiVersion: v1
kind: Secret
metadata:
  name: gcr-proxy-secrets
type: Opaque
data:
  PROXY_AUTH: ${PROXY_AUTH_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-proxy-secrets-file
type: Opaque
data:
  account: ${SERVICE_ACCOUNT_BASE64}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcr-proxy-configmap
data:
  REGISTRY_URL: ${REGISTRY_URL}
  PROXY_URL: ${PROXY_URL}
