apiVersion: v1
kind: Service
metadata:
  name: gcr-proxy-service
spec:
  type: LoadBalancer
  selector:
    app: gcr-proxy
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: "443"
      protocol: TCP
      port: 443
      targetPort: 8443
